### ISSUE TITLE
Image architectures

### ISSUE THREAD

**Issue by samip5** [d8ahazard/FlexTV-docker#1]
Your image does not work on arm32v7, and probably not on others too.

You NEED to use docker manifests to property tag your releases with arch and build them on the specified arch via qemu.

**Comment by samip5** [comment]
The correct way can be seen from here: https://github.com/samip5/FlexTV-docker and https://hub.docker.com/repository/registry-1.docker.io/samip537/docker-flextv/tags

**Comment by d8ahazard** [comment]
Feel free to submit a pull request! 😁

**Comment by samip5** [comment]
Made the PR, and you should know that you cannot use Docker Cloud for multiarch images.

**Comment by karl0ss** [comment]
@samip5 it would appear that your images are not working on my raspberry pi - 

```
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 20-install: executing... 
foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/20-install: Exec format error
foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/20-install: No child process
```

I have run with -
    image: samip537/docker-flextv:arm32v6
and 
    image: samip537/docker-flextv:arm32v7

**Comment by samip5** [comment]
> @samip5 it would appear that your images are not working on my raspberry pi -
> 
> ```
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    1000
> User gid:    1000
> ------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing... 
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 20-install: executing... 
> foreground: warning: unable to spawn /var/run/s6/etc/cont-init.d/20-install: Exec format error
> foreground: fatal: unable to wait for /var/run/s6/etc/cont-init.d/20-install: No child process
> ```
> 
> I have run with -
> image: samip537/docker-flextv:arm32v6
> and
> image: samip537/docker-flextv:arm32v7

I don't currently use 32bit Raspberry Pi's so unfortunately I'm not able to test that.

**Comment by samip5** [comment]
Started a new build, updated docker images should be available in 5 minutes or so. @karl0ss

**Comment by karl0ss** [comment]
Thanks, I am running raspberry pi 4, but i think the raspbian distro is still 32bit?

**Comment by samip5** [comment]
> Thanks, I am running raspberry pi 4, but i think the raspbian distro is still 32bit?

What's the output of `uname -a`? armhf? It should be aarch64 if 64bit.

I'm using Raspberry Pi 4 with [Gentoo ](https://github.com/sakaki-/gentoo-on-rpi-64bit) as a result.
